@startmindmap

* MSA Dependency
++ Service to Service Relationship 
+++ Loose Coupling and High Cohesion
+++ Database per service and consitency, CAP Theorem
+++ Data Storage
+++ Services Communication
++++ Sync and Async
++++ Tracing and Monitoring 




@endmindmap